# Entrega una lista de campeones con su respectiva velocidad de ataque (attackspeed).

PREFIX lol: <http://example.org/lol#>

SELECT ?champ ?value WHERE {
  ?champ a lol:Champion ;
         lol:hasStat ?stat .
  ?stat lol:statName "attackspeed" ;
        lol:statValue ?value .
}
