PREFIX : <http://example.org/lol#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?champ
       (xsd:double(?ad) * (xsd:double(?r) / 100.0) AS ?burst)
WHERE {
  ?champ :hasAttackDamage ?ad ;
         :hasRange ?r .
}
ORDER BY DESC(?burst)
