PREFIX : <http://example.org/lol#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
CONSTRUCT {
  ?c :hasRole :HybridRole .
}
WHERE {
  ?c :hasAttackDamage ?ad ;
     :hasArmor ?arm .
  FILTER(xsd:double(?ad) > 60 && xsd:double(?arm) > 35)
}
