PREFIX : <http://example.org/lol#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?champ
       (xsd:double(?hp) * 0.6 + xsd:double(?armor) * 0.4 AS ?durability)
WHERE {
  ?champ :hasHP ?hp ;
         :hasArmor ?armor .
}
ORDER BY DESC(?durability)
