# Entrega una lista de los campeones que tengan una cantidad de crítico en sus stats base.

PREFIX lol: <http://example.org/lol#>

SELECT ?champ ?crit
WHERE {
  ?champ a lol:Champion ;
         lol:hasStat ?stat .
  ?stat lol:statName "crit" ;
        lol:statValue ?crit .
  FILTER(?crit != 0)
}
ORDER BY DESC(?crit)
