PREFIX : <http://example.org/lol#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

SELECT ?champ ?hp ?armor ?range
WHERE {
  ?champ :hasHP ?hp ;
         :hasArmor ?armor ;
         :hasRange ?range .
  FILTER(xsd:double(?hp) > 600 && xsd:double(?armor) > 40)
}
ORDER BY DESC(?hp)
