# Entrega campeones que no usen maná.

PREFIX lol: <http://example.org/lol#>

SELECT ?champ
WHERE {
  ?champ a lol:Champion ;
         lol:hasStat ?stat .
  ?stat lol:statName "mp" ;
        lol:statValue ?value .
  FILTER (?value < 0.001) .
}
ORDER BY ?champ
