# Entrega una lista de campeones que sean magos (rol Mage), pero tengan daño de ataque mayor a 50.

PREFIX lol: <http://example.org/lol#>

SELECT ?champ ?attackDamage WHERE {
  ?champ a lol:Champion ;
         lol:hasRole lol:Mage ;
         lol:hasStat ?stat .
  ?stat lol:statName "attackdamage" ;
        lol:statValue ?attackDamage .
  FILTER (?attackDamage > 50)
}
