# Entrega una lista de los campeones ordenados descendentemente por su velocidad de movimiento.

PREFIX lol: <http://example.org/lol#>

SELECT ?champ ?ms
WHERE {
  ?champ a lol:Champion ;
         lol:hasStat ?stat .
  ?stat lol:statName "movespeed" ;
        lol:statValue ?ms .
}
ORDER BY DESC(?ms)
