# Entrega una lista de campeones, ordenados descendentemente por su velocidad de ataque.

PREFIX lol: <http://example.org/lol#>

SELECT ?champ ?attackSpeed WHERE {
  ?champ a lol:Champion ;
         lol:hasStat ?stat .
  ?stat lol:statName "attackspeed" ;
        lol:statValue ?attackSpeed .
}
ORDER BY DESC(?attackSpeed)
